// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.6.1
// source: establishment.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EstablishmentsByStoreIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IdStore string `protobuf:"bytes,1,opt,name=idStore,proto3" json:"idStore,omitempty"`
}

func (x *EstablishmentsByStoreIdRequest) Reset() {
	*x = EstablishmentsByStoreIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_establishment_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EstablishmentsByStoreIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EstablishmentsByStoreIdRequest) ProtoMessage() {}

func (x *EstablishmentsByStoreIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_establishment_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EstablishmentsByStoreIdRequest.ProtoReflect.Descriptor instead.
func (*EstablishmentsByStoreIdRequest) Descriptor() ([]byte, []int) {
	return file_establishment_proto_rawDescGZIP(), []int{0}
}

func (x *EstablishmentsByStoreIdRequest) GetIdStore() string {
	if x != nil {
		return x.IdStore
	}
	return ""
}

type EstablishmentByIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IdEstablishment string `protobuf:"bytes,1,opt,name=idEstablishment,proto3" json:"idEstablishment,omitempty"`
}

func (x *EstablishmentByIdRequest) Reset() {
	*x = EstablishmentByIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_establishment_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EstablishmentByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EstablishmentByIdRequest) ProtoMessage() {}

func (x *EstablishmentByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_establishment_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EstablishmentByIdRequest.ProtoReflect.Descriptor instead.
func (*EstablishmentByIdRequest) Descriptor() ([]byte, []int) {
	return file_establishment_proto_rawDescGZIP(), []int{1}
}

func (x *EstablishmentByIdRequest) GetIdEstablishment() string {
	if x != nil {
		return x.IdEstablishment
	}
	return ""
}

type EstablishmentByNameRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *EstablishmentByNameRequest) Reset() {
	*x = EstablishmentByNameRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_establishment_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EstablishmentByNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EstablishmentByNameRequest) ProtoMessage() {}

func (x *EstablishmentByNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_establishment_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EstablishmentByNameRequest.ProtoReflect.Descriptor instead.
func (*EstablishmentByNameRequest) Descriptor() ([]byte, []int) {
	return file_establishment_proto_rawDescGZIP(), []int{2}
}

func (x *EstablishmentByNameRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type EstablishmentsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Establishments []*Establishment `protobuf:"bytes,1,rep,name=establishments,proto3" json:"establishments,omitempty"`
	Success        bool             `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Error          *Error           `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *EstablishmentsResponse) Reset() {
	*x = EstablishmentsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_establishment_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EstablishmentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EstablishmentsResponse) ProtoMessage() {}

func (x *EstablishmentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_establishment_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EstablishmentsResponse.ProtoReflect.Descriptor instead.
func (*EstablishmentsResponse) Descriptor() ([]byte, []int) {
	return file_establishment_proto_rawDescGZIP(), []int{3}
}

func (x *EstablishmentsResponse) GetEstablishments() []*Establishment {
	if x != nil {
		return x.Establishments
	}
	return nil
}

func (x *EstablishmentsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *EstablishmentsResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type EstablishmentResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Establishment *Establishment `protobuf:"bytes,1,opt,name=establishment,proto3" json:"establishment,omitempty"`
	Success       bool           `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Error         *Error         `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *EstablishmentResponse) Reset() {
	*x = EstablishmentResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_establishment_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EstablishmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EstablishmentResponse) ProtoMessage() {}

func (x *EstablishmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_establishment_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EstablishmentResponse.ProtoReflect.Descriptor instead.
func (*EstablishmentResponse) Descriptor() ([]byte, []int) {
	return file_establishment_proto_rawDescGZIP(), []int{4}
}

func (x *EstablishmentResponse) GetEstablishment() *Establishment {
	if x != nil {
		return x.Establishment
	}
	return nil
}

func (x *EstablishmentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *EstablishmentResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type Establishment struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Establishment) Reset() {
	*x = Establishment{}
	if protoimpl.UnsafeEnabled {
		mi := &file_establishment_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Establishment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Establishment) ProtoMessage() {}

func (x *Establishment) ProtoReflect() protoreflect.Message {
	mi := &file_establishment_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Establishment.ProtoReflect.Descriptor instead.
func (*Establishment) Descriptor() ([]byte, []int) {
	return file_establishment_proto_rawDescGZIP(), []int{5}
}

func (x *Establishment) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Establishment) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_establishment_proto protoreflect.FileDescriptor

var file_establishment_proto_rawDesc = []byte{
	0x0a, 0x13, 0x65, 0x73, 0x74, 0x61, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x6d, 0x65, 0x6e, 0x74, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0b, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x3a, 0x0a, 0x1e, 0x45, 0x73, 0x74, 0x61, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x6d,
	0x65, 0x6e, 0x74, 0x73, 0x42, 0x79, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x49, 0x64, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x69, 0x64, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x69, 0x64, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x22, 0x44,
	0x0a, 0x18, 0x45, 0x73, 0x74, 0x61, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x6d, 0x65, 0x6e, 0x74, 0x42,
	0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x28, 0x0a, 0x0f, 0x69, 0x64,
	0x45, 0x73, 0x74, 0x61, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0f, 0x69, 0x64, 0x45, 0x73, 0x74, 0x61, 0x62, 0x6c, 0x69, 0x73, 0x68,
	0x6d, 0x65, 0x6e, 0x74, 0x22, 0x30, 0x0a, 0x1a, 0x45, 0x73, 0x74, 0x61, 0x62, 0x6c, 0x69, 0x73,
	0x68, 0x6d, 0x65, 0x6e, 0x74, 0x42, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x88, 0x01, 0x0a, 0x16, 0x45, 0x73, 0x74, 0x61, 0x62,
	0x6c, 0x69, 0x73, 0x68, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x36, 0x0a, 0x0e, 0x65, 0x73, 0x74, 0x61, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x6d, 0x65,
	0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x45, 0x73, 0x74, 0x61,
	0x62, 0x6c, 0x69, 0x73, 0x68, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x0e, 0x65, 0x73, 0x74, 0x61, 0x62,
	0x6c, 0x69, 0x73, 0x68, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x12, 0x1c, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x06, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x22, 0x85, 0x01, 0x0a, 0x15, 0x45, 0x73, 0x74, 0x61, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x6d,
	0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x34, 0x0a, 0x0d, 0x65,
	0x73, 0x74, 0x61, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x45, 0x73, 0x74, 0x61, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x6d, 0x65,
	0x6e, 0x74, 0x52, 0x0d, 0x65, 0x73, 0x74, 0x61, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x6d, 0x65, 0x6e,
	0x74, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x1c, 0x0a, 0x05, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x06, 0x2e, 0x45, 0x72, 0x72,
	0x6f, 0x72, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x33, 0x0a, 0x0d, 0x45, 0x73, 0x74,
	0x61, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x32, 0xb8,
	0x01, 0x0a, 0x14, 0x45, 0x73, 0x74, 0x61, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x6d, 0x65, 0x6e, 0x74,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x55, 0x0a, 0x19, 0x67, 0x65, 0x74, 0x45, 0x73,
	0x74, 0x61, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x50, 0x65, 0x72, 0x53,
	0x74, 0x6f, 0x72, 0x65, 0x12, 0x1f, 0x2e, 0x45, 0x73, 0x74, 0x61, 0x62, 0x6c, 0x69, 0x73, 0x68,
	0x6d, 0x65, 0x6e, 0x74, 0x73, 0x42, 0x79, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x49, 0x64, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x45, 0x73, 0x74, 0x61, 0x62, 0x6c, 0x69, 0x73,
	0x68, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x49,
	0x0a, 0x14, 0x67, 0x65, 0x74, 0x45, 0x73, 0x74, 0x61, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x6d, 0x65,
	0x6e, 0x74, 0x42, 0x79, 0x49, 0x64, 0x12, 0x19, 0x2e, 0x45, 0x73, 0x74, 0x61, 0x62, 0x6c, 0x69,
	0x73, 0x68, 0x6d, 0x65, 0x6e, 0x74, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x16, 0x2e, 0x45, 0x73, 0x74, 0x61, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x6d, 0x65, 0x6e,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x6a, 0x5a, 0x68, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x65, 0x6d, 0x62, 0x68, 0x31, 0x39, 0x39,
	0x38, 0x2f, 0x67, 0x52, 0x43, 0x50, 0x5f, 0x66, 0x6c, 0x75, 0x74, 0x74, 0x65, 0x72, 0x5f, 0x67,
	0x6f, 0x5f, 0x70, 0x72, 0x6f, 0x6f, 0x66, 0x2d, 0x6f, 0x66, 0x2d, 0x63, 0x6f, 0x6e, 0x63, 0x65,
	0x70, 0x74, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65,
	0x2f, 0x69, 0x6e, 0x66, 0x72, 0x61, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x75, 0x72, 0x65, 0x2f,
	0x73, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x72, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_establishment_proto_rawDescOnce sync.Once
	file_establishment_proto_rawDescData = file_establishment_proto_rawDesc
)

func file_establishment_proto_rawDescGZIP() []byte {
	file_establishment_proto_rawDescOnce.Do(func() {
		file_establishment_proto_rawDescData = protoimpl.X.CompressGZIP(file_establishment_proto_rawDescData)
	})
	return file_establishment_proto_rawDescData
}

var file_establishment_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_establishment_proto_goTypes = []interface{}{
	(*EstablishmentsByStoreIdRequest)(nil), // 0: EstablishmentsByStoreIdRequest
	(*EstablishmentByIdRequest)(nil),       // 1: EstablishmentByIdRequest
	(*EstablishmentByNameRequest)(nil),     // 2: EstablishmentByNameRequest
	(*EstablishmentsResponse)(nil),         // 3: EstablishmentsResponse
	(*EstablishmentResponse)(nil),          // 4: EstablishmentResponse
	(*Establishment)(nil),                  // 5: Establishment
	(*Error)(nil),                          // 6: Error
}
var file_establishment_proto_depIdxs = []int32{
	5, // 0: EstablishmentsResponse.establishments:type_name -> Establishment
	6, // 1: EstablishmentsResponse.error:type_name -> Error
	5, // 2: EstablishmentResponse.establishment:type_name -> Establishment
	6, // 3: EstablishmentResponse.error:type_name -> Error
	0, // 4: EstablishmentService.getEstablishmentsPerStore:input_type -> EstablishmentsByStoreIdRequest
	1, // 5: EstablishmentService.getEstablishmentById:input_type -> EstablishmentByIdRequest
	3, // 6: EstablishmentService.getEstablishmentsPerStore:output_type -> EstablishmentsResponse
	4, // 7: EstablishmentService.getEstablishmentById:output_type -> EstablishmentResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_establishment_proto_init() }
func file_establishment_proto_init() {
	if File_establishment_proto != nil {
		return
	}
	file_error_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_establishment_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EstablishmentsByStoreIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_establishment_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EstablishmentByIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_establishment_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EstablishmentByNameRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_establishment_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EstablishmentsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_establishment_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EstablishmentResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_establishment_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Establishment); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_establishment_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_establishment_proto_goTypes,
		DependencyIndexes: file_establishment_proto_depIdxs,
		MessageInfos:      file_establishment_proto_msgTypes,
	}.Build()
	File_establishment_proto = out.File
	file_establishment_proto_rawDesc = nil
	file_establishment_proto_goTypes = nil
	file_establishment_proto_depIdxs = nil
}
