proto: 
	protoc --go_out=src/module/infrastructure/serializer/grpc/pb --go_opt=paths=source_relative \
	--go-grpc_out=src/module/infrastructure/serializer/grpc/pb --go-grpc_opt=paths=source_relative \
	../protos/*.proto

.PHONY: proto