-- MySQL Script generated by MySQL Workbench
-- Sun 15 Jan 2023 06:45:58 PM -05
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema flutter_go
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema flutter_go
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `flutter_go` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
-- -----------------------------------------------------
-- Schema marcodb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema marcodb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `marcodb` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `flutter_go` ;

-- -----------------------------------------------------
-- Table `flutter_go`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `flutter_go`.`products` (
  `id` VARCHAR(36) NOT NULL,
  `name` VARCHAR(155) NOT NULL,
  `sku` VARCHAR(45) NOT NULL,
  `bar_code` VARCHAR(45) NOT NULL,
  `abbreviated_name` VARCHAR(9) NOT NULL,
  `pic_prod_url` VARCHAR(455) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `flutter_go`.`stores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `flutter_go`.`stores` (
  `id` VARCHAR(36) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `flutter_go`.`establishments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `flutter_go`.`establishments` (
  `id` VARCHAR(36) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `store_id` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_store_branches_stores_idx` (`store_id` ASC) VISIBLE,
  CONSTRAINT `fk_store_branches_stores`
    FOREIGN KEY (`store_id`)
    REFERENCES `flutter_go`.`stores` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `flutter_go`.`intentories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `flutter_go`.`intentories` (
  `id` VARCHAR(36) NOT NULL,
  `establishment_id` VARCHAR(36) NOT NULL,
  `product_id` VARCHAR(36) NOT NULL,
  `price` DOUBLE NOT NULL,
  `stock` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_intentories_store_branches1_idx` (`establishment_id` ASC) VISIBLE,
  INDEX `fk_intentories_products1_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_intentories_products1`
    FOREIGN KEY (`product_id`)
    REFERENCES `flutter_go`.`products` (`id`),
  CONSTRAINT `fk_intentories_store_branches1`
    FOREIGN KEY (`establishment_id`)
    REFERENCES `flutter_go`.`establishments` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `flutter_go`.`members`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `flutter_go`.`members` (
  `id` VARCHAR(36) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `pic_profile_url` VARCHAR(455) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `flutter_go`.`transactions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `flutter_go`.`transactions` (
  `id` VARCHAR(36) NOT NULL,
  `date` DATETIME NOT NULL,
  `member_id` VARCHAR(36) NOT NULL,
  `total` DOUBLE NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_transactions_members1_idx` (`member_id` ASC) VISIBLE,
  CONSTRAINT `fk_transactions_members1`
    FOREIGN KEY (`member_id`)
    REFERENCES `flutter_go`.`members` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `flutter_go`.`transaction_details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `flutter_go`.`transaction_details` (
  `id` VARCHAR(36) NOT NULL,
  `quantity` INT NOT NULL,
  `intentorie_id` VARCHAR(36) NOT NULL,
  `transaction_id` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_transaction_details_intentories1_idx` (`intentorie_id` ASC) VISIBLE,
  INDEX `fk_transaction_details_transactions1_idx` (`transaction_id` ASC) VISIBLE,
  CONSTRAINT `fk_transaction_details_intentories1`
    FOREIGN KEY (`intentorie_id`)
    REFERENCES `flutter_go`.`intentories` (`id`),
  CONSTRAINT `fk_transaction_details_transactions1`
    FOREIGN KEY (`transaction_id`)
    REFERENCES `flutter_go`.`transactions` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

USE `marcodb` ;

-- -----------------------------------------------------
-- Table `marcodb`.`grupos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `marcodb`.`grupos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `marcodb`.`estudiantes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `marcodb`.`estudiantes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(155) NOT NULL,
  `apellidos` VARCHAR(155) NOT NULL,
  `edad` VARCHAR(45) NOT NULL,
  `codigo_estudiantil` VARCHAR(45) NOT NULL,
  `turno` VARCHAR(45) NOT NULL,
  `sexo` VARCHAR(45) NOT NULL,
  `carrera` VARCHAR(155) NOT NULL,
  `tipo_de_colegio` VARCHAR(45) NOT NULL,
  `area_de_residencia` VARCHAR(45) NOT NULL,
  `nivel_educativo_padre` VARCHAR(45) NOT NULL,
  `nivel_educativo_madre` VARCHAR(45) NOT NULL,
  `trabaja` VARCHAR(2) NOT NULL,
  `grupos_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_estudiantes_grupos1_idx` (`grupos_id` ASC) VISIBLE,
  CONSTRAINT `fk_estudiantes_grupos1`
    FOREIGN KEY (`grupos_id`)
    REFERENCES `marcodb`.`grupos` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `marcodb`.`lecturas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `marcodb`.`lecturas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(455) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `marcodb`.`preguntas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `marcodb`.`preguntas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `pregunta` VARCHAR(455) NOT NULL,
  `lecturas_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_preguntas_lecturas_idx` (`lecturas_id` ASC) VISIBLE,
  CONSTRAINT `fk_preguntas_lecturas`
    FOREIGN KEY (`lecturas_id`)
    REFERENCES `marcodb`.`lecturas` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `marcodb`.`opciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `marcodb`.`opciones` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `opcion` VARCHAR(455) NOT NULL,
  `preguntas_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_opciones_preguntas1_idx` (`preguntas_id` ASC) VISIBLE,
  CONSTRAINT `fk_opciones_preguntas1`
    FOREIGN KEY (`preguntas_id`)
    REFERENCES `marcodb`.`preguntas` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 61
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `marcodb`.`respuestas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `marcodb`.`respuestas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `opciones_id` INT NOT NULL,
  `estudiantes_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_respuestas_opciones1_idx` (`opciones_id` ASC) VISIBLE,
  INDEX `fk_respuestas_estudiantes1_idx` (`estudiantes_id` ASC) VISIBLE,
  CONSTRAINT `fk_respuestas_estudiantes1`
    FOREIGN KEY (`estudiantes_id`)
    REFERENCES `marcodb`.`estudiantes` (`id`),
  CONSTRAINT `fk_respuestas_opciones1`
    FOREIGN KEY (`opciones_id`)
    REFERENCES `marcodb`.`opciones` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
