-- MySQL Script generated by MySQL Workbench
-- Sun Jan 15 11:14:23 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema flutter_go
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema flutter_go
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `flutter_go` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `flutter_go` ;

-- -----------------------------------------------------
-- Table `flutter_go`.`stores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `flutter_go`.`stores` (
  `id` VARCHAR(36) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `flutter_go`.`store_branches`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `flutter_go`.`store_branches` (
  `id` VARCHAR(36) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `stores_id` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_store_branches_stores_idx` (`stores_id` ASC) VISIBLE,
  CONSTRAINT `fk_store_branches_stores`
    FOREIGN KEY (`stores_id`)
    REFERENCES `flutter_go`.`stores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `flutter_go`.`members`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `flutter_go`.`members` (
  `id` VARCHAR(36) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `pic_profile_url` VARCHAR(455) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `flutter_go`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `flutter_go`.`products` (
  `id` VARCHAR(36) NOT NULL,
  `name` VARCHAR(155) NOT NULL,
  `sku` VARCHAR(45) NOT NULL,
  `bar_code` VARCHAR(45) NOT NULL,
  `abbreviated_name` VARCHAR(9) NOT NULL,
  `pic_prod_url` VARCHAR(455) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `flutter_go`.`transactions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `flutter_go`.`transactions` (
  `id` VARCHAR(36) NOT NULL,
  `date` DATETIME NOT NULL,
  `members_id` VARCHAR(36) NOT NULL,
  `total` DOUBLE NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_transactions_members1_idx` (`members_id` ASC) VISIBLE,
  CONSTRAINT `fk_transactions_members1`
    FOREIGN KEY (`members_id`)
    REFERENCES `flutter_go`.`members` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `flutter_go`.`intentories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `flutter_go`.`intentories` (
  `id` VARCHAR(36) NOT NULL,
  `store_branches_id` VARCHAR(36) NOT NULL,
  `products_id` VARCHAR(36) NOT NULL,
  `price` DOUBLE NOT NULL,
  `stock` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_intentories_store_branches1_idx` (`store_branches_id` ASC) VISIBLE,
  INDEX `fk_intentories_products1_idx` (`products_id` ASC) VISIBLE,
  CONSTRAINT `fk_intentories_store_branches1`
    FOREIGN KEY (`store_branches_id`)
    REFERENCES `flutter_go`.`store_branches` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_intentories_products1`
    FOREIGN KEY (`products_id`)
    REFERENCES `flutter_go`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `flutter_go`.`transaction_details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `flutter_go`.`transaction_details` (
  `id` VARCHAR(36) NOT NULL,
  `quantity` INT NOT NULL,
  `intentories_id` VARCHAR(36) NOT NULL,
  `transactions_id` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_transaction_details_intentories1_idx` (`intentories_id` ASC) VISIBLE,
  INDEX `fk_transaction_details_transactions1_idx` (`transactions_id` ASC) VISIBLE,
  CONSTRAINT `fk_transaction_details_intentories1`
    FOREIGN KEY (`intentories_id`)
    REFERENCES `flutter_go`.`intentories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transaction_details_transactions1`
    FOREIGN KEY (`transactions_id`)
    REFERENCES `flutter_go`.`transactions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
